name: "ChRIS Backend"
description: "Bring up ephemeral instances of CUBE, pfcon, pman, pfioh, swift, and ChRIS_store"
author: "FNNDSC"
inputs:
  plugins:
    description: "List of plugins to register, separated by whitespace."
    required: false
    default: ''

runs:
  using: node20
  main: wrapper.js
  post: wrapper.js

branding:
  color: "blue"
  icon: "box"
