name: "ChRIS Backend"
description: "Bring up ephemeral instances of CUBE, pfcon, pman, pfioh, swift, and ChRIS_store"
author: "FNNDSC"
inputs:
  plugins:
    description: "List of plugins to register, separated by whitespace."
    required: false
    default: ''
outputs:
  cube-user:
    description: "ChRIS user"
    value: "chris:chris1234"
  cube-url:
    description: "CUBE URL"
    value: "http://localhost:8010/api/v1/"
runs:
  using: node16
  main: wrapper.js
  post: wrapper.js

branding:
  color: "blue"
  icon: "box"
