# an ephemeral instance of ChRIS backend services for local development
#
# warning: /var/run/docker.sock is mounted into some services (notably pman)

version: '3.9'

services:
  chrisomatic:
    image: ghcr.io/fnndsc/chrisomatic:0.4.1
    networks:
      - local
    volumes:
      - "./chrisomatic.yml:/chrisomatic.yml:ro"
      - "/var/run/docker.sock:/var/run/docker.sock:rw"
    userns_mode: host
    depends_on:
      - chris
      - chris_store
    profiles:
      - tools
  chris:
    container_name: chris
    image: ghcr.io/fnndsc/cube:4.0.0.pre11
    ports:
      - "8000:8000"
    depends_on:
      - chris_db
      - swift
      - queue
    networks:
      - local
    env_file: secrets.env
    environment:
      DJANGO_DB_MIGRATE: "on"
      DJANGO_COLLECTSTATIC: "on"
    labels:
      org.chrisproject.role: "ChRIS ultron backEnd"
      org.chrisproject.miniChRIS: "miniChRIS"
  worker:
    image: ghcr.io/fnndsc/cube:4.0.0.pre11
    command: celery -A core worker -c 4 -l info -Q main1,main2
    env_file: secrets.env
    environment:
      DJANGO_DB_MIGRATE: "off"
      DJANGO_COLLECTSTATIC: "off"
    depends_on:
      - chris_db
      - swift
      - queue
      - pfcon
    restart: on-failure
    networks:
      - local
  worker_periodic:
    image: ghcr.io/fnndsc/cube:4.0.0.pre11
    environment:
      DJANGO_DB_MIGRATE: "off"
      DJANGO_COLLECTSTATIC: "off"
    command: celery -A core worker -c 2 -l info -Q periodic
    env_file: secrets.env
    depends_on:
      - chris_db
      - queue
    restart: on-failure
    networks:
      - local
  scheduler:
    image: ghcr.io/fnndsc/cube:4.0.0.pre11
    command: celery -A core beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    env_file: secrets.env
    environment:
      DJANGO_DB_MIGRATE: "off"
      DJANGO_COLLECTSTATIC: "off"
    depends_on:
      - chris_db
      - queue
    restart: on-failure
    networks:
      - local
  chris_db:
    image: docker.io/library/postgres:13
    env_file: secrets.env
    restart: on-failure
    volumes:
      - chris_db_data:/var/lib/postgresql
    networks:
      - local
  queue:
    image: docker.io/library/rabbitmq:3
    restart: on-failure
    networks:
      - local

  graphql-engine:
    image: hasura/graphql-engine:v2.27.0
    ports:
      - "8090:8080"
    restart: always
    environment:
      ## postgres database to store Hasura metadata
      ## TODO maybe we should use a separate one...
      HASURA_GRAPHQL_METADATA_DATABASE_URL: postgres://chris:chris1234@chris_db:5432/chris
      ## this env var can be used to add the above postgres database to Hasura as a data source. this can be removed/updated based on your needs
      PG_DATABASE_URL: postgres://chris:chris1234@chris_db:5432/chris
      ## enable the console served by server
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      ## enable debugging mode. It is recommended to disable this in production
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      ## uncomment next line to run console offline (i.e load console assets from server instead of CDN)
      HASURA_GRAPHQL_CONSOLE_ASSETS_DIR: /srv/console-assets
      ## uncomment next line to set an admin secret
      # HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
      HASURA_GRAPHQL_METADATA_DEFAULTS: '{"backend_configs":{"dataconnector":{"athena":{"uri":"http://data-connector-agent:8081/api/v1/athena"},"mariadb":{"uri":"http://data-connector-agent:8081/api/v1/mariadb"},"mysql8":{"uri":"http://data-connector-agent:8081/api/v1/mysql"},"oracle":{"uri":"http://data-connector-agent:8081/api/v1/oracle"},"snowflake":{"uri":"http://data-connector-agent:8081/api/v1/snowflake"}}}}'
    depends_on:
      data-connector-agent:
        condition: service_healthy
    networks:
      - local
  data-connector-agent:
    image: hasura/graphql-data-connector:v2.27.0
    restart: always
    ports:
      - 8081:8081
    environment:
      QUARKUS_LOG_LEVEL: ERROR # FATAL, ERROR, WARN, INFO, DEBUG, TRACE
      ## https://quarkus.io/guides/opentelemetry#configuration-reference
      QUARKUS_OPENTELEMETRY_ENABLED: "false"
      ## QUARKUS_OPENTELEMETRY_TRACER_EXPORTER_OTLP_ENDPOINT: http://jaeger:4317
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/api/v1/athena/health"]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 5s
    networks:
      - local

  chris_store:
    container_name: chris_store
    image: ghcr.io/fnndsc/chris_store:2.2.0
    environment:
      - DJANGO_DB_MIGRATE=on
      - DJANGO_SETTINGS_MODULE=config.settings.production
      - DJANGO_ALLOWED_HOSTS=*
      - DJANGO_SECRET_KEY=secret
      - DJANGO_CORS_ALLOW_ALL_ORIGINS=true
      - DJANGO_CORS_ALLOWED_ORIGINS=https://babymri.org
      - DJANGO_SECURE_PROXY_SSL_HEADER=
      - DJANGO_USE_X_FORWARDED_HOST=false
      - DATABASE_HOST=chris_store_db
      - DATABASE_PORT=5432
      - POSTGRES_DB=chris_store
      - POSTGRES_USER=chris
      - POSTGRES_PASSWORD=chirs1234
    ports:
      - "8010:8010"
    depends_on:
      - chris_store_db
    networks:
      local:
        aliases:
          - chrisstore.local
  chris_store_db:
    image: docker.io/library/postgres:13
    environment:
      - POSTGRES_DB=chris_store
      - POSTGRES_USER=chris
      - POSTGRES_PASSWORD=chirs1234
    volumes:
      - chris_store_db_data:/var/lib/postgresql
    networks:
      - local
    labels:
      name: "ChRIS_store MySQL Database"

  swift:
    image: docker.io/fnndsc/docker-swift-onlyone:latest
    init: true
    environment:
      - SWIFT_USERNAME=chris:chris1234
      - SWIFT_KEY=testing
    ports:
      - "8080:8080"
    volumes:
      - swift_storage:/srv
    networks:
      - local

  pfcon:
    container_name: pfcon
    image: ghcr.io/fnndsc/pfcon:5.0.0
    environment:
      COMPUTE_SERVICE_URL: http://pman:5010/api/v1/
      SECRET_KEY: secret
      PFCON_USER: pfcon
      PFCON_PASSWORD: pfcon1234
    ports:
      - "5005:5005"
    volumes:
      - remote:/var/local/storeBase
    networks:
      local:
        aliases:
          - pfcon.host
      remote:
    labels:
      org.chrisproject.role: "pfcon"
    user: "10100"

  pman:
    image: ghcr.io/fnndsc/pman:5.0.0.a5
    container_name: pman
    environment:
      CONTAINER_ENV: docker
      CONTAINER_USER: "10100:"
      ENABLE_HOME_WORKAROUND: "yes"
      JOB_LABELS: "org.chrisproject.miniChRIS=plugininstance"
      SECRET_KEY: secret
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
    depends_on:
      - pfcon
    ports:
      - "5010:5010"
    networks:
      - remote
    userns_mode: "host"
    labels:
      org.chrisproject.role: "pman"

  chris_ui:
    image: ghcr.io/fnndsc/chris_ui:20230511.247-3c1675ff
    command: sirv --host --single
    environment:
      REACT_APP_CHRIS_UI_URL: http://localhost:8000/api/v1/
      REACT_APP_PFDCM_URL: http://localhost:4005/
    ports:
      - "8020:3000"
  chris_store_ui:
    image: ghcr.io/fnndsc/chris_store_ui:0.2.1
    command: sirv --host --single
    environment:
      REACT_APP_STORE_URL: http://localhost:8010/api/v1/
    ports:
      - "8021:3000"

  orthanc:
    image: docker.io/jodogne/orthanc-plugins:1.11.0
    volumes:
      - ./orthanc.json:/etc/orthanc/orthanc.json:ro
      - orthanc:/var/lib/orthanc/db
    ports:
      - "4242:4242"
      - "8042:8042"
    networks:
      - pacs

  pfdcm:
    image: ghcr.io/fnndsc/pfdcm:3.0.12
    container_name: pfdcm
    volumes:
      - pfdcm:/home/dicom:rw
      - ./pfdcm-services:/home/dicom/services:ro
    ports:
      - "4005:4005"
    networks:
      - pacs
      - local
    user: "10100"

  pfdcm-listener:
    image: ghcr.io/fnndsc/pfdcm:3.0.12
    command: sh -c "mkdir -vp /tmp/data && storescp --fork -od /tmp/data -pm -sp -xcr '/usr/local/bin/px-repack --xcrdir \"#p\" --xcrfile \"#f\" --verbosity 0 --logdir /home/dicom/log --datadir /home/dicom/data --cleanup' 11113"
    volumes:
      - pfdcm:/home/dicom:rw
    networks:
      - pacs
    user: "10100"
    restart: on-failure
    depends_on:
      - pfdcm-nonroot-user-volume-fix

  # Non-root container user workarounds

  pfdcm-nonroot-user-volume-fix:
    image: docker.io/library/alpine:latest
    volumes:
      - pfdcm:/home/dicom:rw
    user: root
    command: chown 10100 /home/dicom
    restart: "no"

  pfcon-nonroot-user-volume-fix:
    image: docker.io/library/alpine:latest
    volumes:
      - remote:/var/local/storeBase:rw
    user: root
    command: chown 10100 /var/local/storeBase
    restart: "no"

networks:
  local:
  remote:
  pacs:

volumes:
  chris_db_data:
  chris_store_db_data:
  swift_storage:
  remote:
  orthanc:
  pfdcm:
