# run everything just to make sure it works!

name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: JS unit tests
        run: node wrapper.js test
      - name: miniChRIS
        id: cube
        uses: ./
        with:
          plugins: |
            pl-mri-preview
            pl-re-sub
      - name: Run pl-dircopy
        run: ./test.sh
      - name: Check extra plugins installed
        run: |
          all_plugin_names="$(
            curl -sLu 'chris:chris1234' 'http://localhost:8000/api/v1/plugins/' \
              -H 'Accept: application/json'
          )"

          function assert_has () {
            [[ "$all_plugin_names" = *"$1"* ]]
          }

          set -e
          assert_has pl-mri-preview
          assert_has pl-re-sub
