# run everything just to make sure it works!

name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: miniChRIS
        uses: ./
      - name: Run pl-dircopy
        run: ./test.sh
